
version: "3"

services:
  api:
    env_file:
      ./env/env.dev
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      # map your pc port (first number) to docker port (second number)
      - "8000:8000"
  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U","postgres","-d","postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:


