version: "3"

services:
  api:
    command: "poetry run python manage.py runserver --settings tp_django.settings.dev 0.0.0.0:8000"
    build: 
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - .:/app
    ports:
      # map your pc port (first number) to docker port (second number)
      - "8000:8000"
  # db:
  #   image: postgres:latest
  #   restart: always
  #   environment: 
