version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    env_file:
      ./frontend/.env/.env.dev

  backend:
    build: 
      context: ./backend
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      ./backend/.env/dev/.env.django.dev
    ports:
      - "8000:8000" # map your container port (second number) to your localhost port (first number)
    volumes:
      - ./backend:/backend
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    hostname: db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      ./backend/.env/dev/.env.postgres.dev
    ports:
      - "5433:5432" # map the containter port 5433 to your localhost port 5434  
    healthcheck:
      test: [ "CMD", "pg_isready", "-U","postgres","-d","postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:


