version: "3"

services:
  api:
    build: 
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    hostname: db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
