version: "3"

services:
  api:
    env_file:
      ./env/dev/env.django.dev
    command: sh -c "poetry run python manage.py makemigrations &&
      poetry run python manage.py migrate &&
      poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000" # map your container port (second number) to your localhost port (first number)
  db:
    env_file:
      ./env/dev/env.postgres.dev
    ports:
      - "5434:5433" # map the containter port 5433 to your localhost port 5434  
    healthcheck:
      test: [ "CMD", "pg_isready", "-U","postgres","-d","postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5



