version: "3"

services:
  api:
    env_file:
      ./env/prod/env.django.prod
    command: sh -c "poetry run python manage.py makemigrations &&
      poetry run python manage.py migrate &&
      poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000" # map your container port (second number) to your localhost port (first number)
  db:
    env_file:
      ./env/prod/env.postgres.prod
    ports:
      - "5433:5432" # map the containter port 5432 to your localhost port 5433  
    healthcheck:
      test: [ "CMD", "pg_isready", "-U","postgres","-d","postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5



